### ISSUE TITLE
There is no registration flow on https://forum.taikozuerich.ch/ 

### ISSUE THREAD

**Issue by ikondrat** [Marco-Peter/TaikoBot#22]
Hi Marco

Looks like I havn't managed to find registration for the new user on https://forum.taikozuerich.ch/

**Comment by Marco-Peter** [comment]
The forum is working invitation based.

When you register on https://taikobot.taikozuerich.ch you will receive a confirmation email to access the forum.
Please inform me, or reopen the  issue if the procedure described in [this slack message](https://taikozuerich.slack.com/archives/CCKSRHZQV/p1709896500586579) is not working.

The reason is that I plan to put both applications under a common login, but this needs a bit more work.

**Comment by Marco-Peter** [comment]
Just saw that you don't are on our Slack channel.
So if you have troubles registering, please write me here or contact Micah, so that we can resolve it. Thank you ;-)
